### PR TITLE
gh-pages splash page

### PR DESCRIPTION
**Pull request by aeharding**
Just a starter for further github.io documentation.

### CODE REVIEW

**Comment by PiyushMattoo** [comment]
Any reason why you're using fonts hosted off of Google CDN?

**Comment by aeharding** [comment]
It's a pretty standard to use the Google CDN for fonts (load fast too, since they can be cached cross-domain).

http://www.google.com/fonts/

**Comment by PiyushMattoo** [comment]
Just thinking if Google font had the same fate as Google reader, we would be left with no style:-)
I had a workplace where I stayed away from externally hosted CDN's as lots of computers only had intranet and no internet access hence those applications won't work with CDNs.

**Comment by aeharding** [comment]
Gotcha. :+1:  Actually, I probably should have added an OS-based fallback font, like this: `font-family: 'Lato', sans-serif;`
```

**Comment by PiyushMattoo** [comment]
image

**Pull request merged**
